#!/bin/sh
echo "🧊 Running post-commit quality gates..."
if [ -f "./tools/.codacy-tokens" ]; then
  echo "🔑 Loading Codacy tokens..."
  . ./tools/.codacy-tokens
fi
echo "✅ Post-commit tasks completed"
