# .github/workflows/testing.yml
# DISABLED: Functionality consolidated into build-test-deploy.yml
# This workflow was causing redundant CI runs and runner contention
# All testing (unit, e2e, type-check, lint) is handled by the main workflow

name: Testing Pipeline (DISABLED)

on:
  # Disabled to prevent redundant CI runs
  # All testing functionality moved to build-test-deploy.yml
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run this redundant workflow (not recommended)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20.19.1'
  PNPM_VERSION: '10'

jobs:
  # All jobs moved to build-test-deploy.yml
  disabled-notice:
    name: Workflow Disabled Notice
    runs-on: [self-hosted, linux]
    timeout-minutes: 1
    if: github.event.inputs.force_run == 'true'
    steps:
      - name: Notice
        run: |
          echo "⚠️ This workflow has been disabled to eliminate redundancy"
          echo "All testing functionality is now in build-test-deploy.yml"
          echo "Please use the main workflow instead"
